// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>

/**
 * Open Source Initiative OSI - The MIT License (MIT):Licensing
 * [OSI Approved License]
 * The MIT License (MIT)
 *
 * Copyright (c) 2011 Igor France
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace Sage.Test.Configuration
{
	using Machine.Specifications;
	using Sage.Configuration;

	[Subject(typeof(ProjectConfiguration)), Tags(Categories.Configuration)]
	public class When_checking_developer_IP_addresses
	{
		private static ProjectConfiguration config;

		private Because of = () => config = ProjectConfiguration.Current;

		private It Should_return_true_for_local_adresses1 = () => config.IsDeveloperIp("127.0.0.1").ShouldBeTrue();
		private It Should_return_true_for_local_adresses2 = () => config.IsDeveloperIp("::1").ShouldBeTrue();
		private It Should_return_true_for_lan_adresses1 = () => config.IsDeveloperIp("172.16.4.12").ShouldBeTrue();
		private It Should_return_true_for_lan_adresses32 = () => config.IsDeveloperIp("10.180.5.4").ShouldBeTrue();
	}
}
