// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>

/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace Sage.Test.Configuration
{
	using System.Linq;
	using System.Xml;

	using Machine.Specifications;
	using Sage.Configuration;

	[Subject(typeof(ProjectConfiguration)), Tags(Categories.Configuration)]
	public class When_checking_developer_IP_addresses
	{
		private static ProjectConfiguration config;

		private Because of = () => config = Project.Configuration;

		private It Should_return_true_for_local_adresses1 = () => config.Environment.IsDeveloperIp("127.0.0.1").ShouldBeTrue();
		private It Should_return_true_for_local_adresses2 = () => config.Environment.IsDeveloperIp("::1").ShouldBeTrue();
		private It Should_return_true_for_lan_adresses1 = () => config.Environment.IsDeveloperIp("172.16.4.12").ShouldBeTrue();
		private It Should_return_true_for_lan_adresses32 = () => config.Environment.IsDeveloperIp("10.180.5.4").ShouldBeTrue();
	}

	[Subject(typeof(ProjectConfiguration)), Tags(Categories.Configuration)]
	public class If_default_locale_doesnt_exist
	{
		private static ProjectConfiguration config;

		private Because of = () =>
		{
			config = ProjectConfiguration.Create(new XmlDocument { InnerXml =
				@"<project xmlns='http://www.cycle99.com/schemas/sage/configuration/project.xsd' defaultLocale='en'>
					<internationalization>
						<locale name='us' dictionaryNames='us,en' resourceNames='us,en,default'>
							<format culture='en-us' shortDate='MMMM d, yyyy' longDate='D'/>
						</locale>
					</internationalization>
				</project>"});

			System.Diagnostics.Debug.WriteLine(config.Locales.Count);
		};

		private It Should_set_the_default_locale_to_the_first_defined_locale = () => 
			config.DefaultLocale.ShouldEqual(config.Locales.First().Key);
	}
}
