//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

namespace Sage.Test.Configuration
{
	using Machine.Specifications;
	using Sage.Configuration;

	[Subject(typeof(ProjectConfiguration)), Tags(Categories.Configuration)]
	public class When_checking_developer_IP_addresses
	{
		private static ProjectConfiguration config;

		private Because of = () => config = ProjectConfiguration.Current;

		private It Should_return_true_for_local_adresses1 = () => config.IsDeveloperIp("127.0.0.1").ShouldBeTrue();
		private It Should_return_true_for_local_adresses2 = () => config.IsDeveloperIp("::1").ShouldBeTrue();
		private It Should_return_true_for_lan_adresses1 = () => config.IsDeveloperIp("172.16.4.12").ShouldBeTrue();
		private It Should_return_true_for_lan_adresses32 = () => config.IsDeveloperIp("10.180.5.4").ShouldBeTrue();
	}
}
