//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local
namespace Sage.Test.ResourceManagement
{
	using Machine.Specifications;

	using Sage.Configuration;
	using Sage.ResourceManagement;

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_default_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"c:\somewhere\file-default.txt", category);
		private It Should_have_locale_default = () => resourceName.Locale.ShouldEqual("default");
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_locale_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"d:\somewhere\file-{locale}.txt", category);
		private It Should_have_locale_locale = () => resourceName.Locale.ShouldEqual("{locale}");
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_no_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"c:\somewhere\file-example.txt", category);
		private It Should_have_no_locale = () => resourceName.Locale.ShouldBeNull();
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"c:\somewhere\file-uk.txt", category);
		private It Should_not_be_null = () => resourceName.ShouldNotBeNull();
		private It Should_have_locale_uk = () => resourceName.Locale.ToLower().ShouldEqual("uk");
		private It Should_have_fileproperty_file = () => resourceName.FileName.ShouldEqual("file");
		private It Should_have_correct_pathproperty = () => resourceName.FileDirectory.ShouldEqual("c:\\somewhere");
		private It Should_have_correct_extension = () => resourceName.Extension.ShouldEqual(".txt");
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_unknown_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"d:\somewhere\file-rr.txt", category);
		private It Should_have_no_locale = () => resourceName.Locale.ShouldBeNull();
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_la_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"G:\default\flash\xml\mastfoot\techfit-la.xml", category);
		private It Should_have_no_locale_la = () => resourceName.Locale.ToLower().ShouldEqual("la");
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_es_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"G:\default\flash\xml\mastfoot\techfit-es.xml", category);
		private It Should_have_no_locale_la = () => resourceName.Locale.ToLower().ShouldEqual("es");
	}

	[Subject(typeof(ResourceName)), Tags(Categories.ResourceManagement)]
	public class When_getting_a_resource_with_tw_locale_suffix
	{
		private static SageContext context = Mother.CreateSageContext("default", "com");
		private static CategoryInfo category = context.ProjectConfiguration.Categories["default"];
		private static ResourceName resourceName;

		private Because of = () => resourceName = new ResourceName(@"G:\default\flash\xml\mastfoot\techfit-tw.xml", category);
		private It Should_have_no_locale_la = () => resourceName.Locale.ToLower().ShouldEqual("tw");
	}
}
