//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local
namespace Sage.Test.ResourceManagement
{
	using Machine.Specifications;

	using Sage.Configuration;
	using Sage.ResourceManagement;

	[Subject(typeof(XmlResource)), Tags(Categories.ResourceManagement)]
	public class When_loading_an_xml_resource
	{
		static SageContext context = Mother.CreateSageContext("default", "fr");

		It Should_load_the_french_file_properly = () =>
			new XmlResource(context.MapPath("~/assets/default/views/home/index.xml"), context)
				.Load("fr")
				.DocumentElement.InnerText.ShouldContain("french");

		It Should_load_the_german_file_properly = () =>
			new XmlResource(context.MapPath("~/assets/default/views/home/index.xml"), context)
				.Load("de")
				.DocumentElement.InnerText.ShouldContain("german");
	}
}