//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------
namespace Sage.Test
{
	using System;

	using Machine.Specifications;

	using Sage.Views;

	[Subject(typeof(XsltTransform)), Tags(Categories.ResourceManagement)]
	public class When_opening_an_xslt_file
	{
		private static SageContext context = Mother.CreateSageContext(string.Empty);

		private It Should_store_that_file_in_cache = () =>
		{
			throw new NotImplementedException();
		};

		private It Should_reuse_that_file_if_exists_in_cache = () =>
		{
			throw new NotImplementedException();
		};

		private It Should_pick_the_fresh_version_if_the_source_file_changes = () =>
		{
			throw new NotImplementedException();
		};

		private It Should_pick_the_fresh_version_if_any_dependencies_change = () =>
		{
			throw new NotImplementedException();
		};

		private It Should_use_project_default_stylesheet_if_specific_one_is_missing_and_project_default_exists = () =>
		{
			throw new NotImplementedException();
		};

		private It Should_use_category_default_stylesheet_if_specific_one_is_missing_and_category_default_exists = () =>
		{
			throw new NotImplementedException();
		};

		private It Should_use_builtin_default_stylesheet_if_specific_one_is_missing_and_no_other_default_stylesheets_exist = () =>
		{
			throw new NotImplementedException();
		};
	}
}
