//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------
namespace Sage.Test
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	using Machine.Specifications;

	using Sage.Xml;

	[Subject(typeof(XsltRegistry))]
	public class When_opening_a_standard_xslt_file
	{
		private static SageContext context = Mother.CreateSageContext(string.Empty);

		//private static string stylesheetPath1 = Utilities.ExpandResourcePath
		private It Should_store_that_file_in_cache = () =>
		{
			//context.Path.

		};

		private It Should_reuse_that_file_if_exists_in_cache;
		// XsltRegistry
		// When opening an xslt file
		// Should store that file in cache
		// Should reuse that file from cache if it exists in cache
		// Should cache and reuse the parent stylesheet if this stylesheet is empty
		// Should use the fresh version if the source file changes
		// Should use the fresh version if the parent stylesheet changes
	}

	[Subject(typeof(XsltRegistry))]
	public class When_opening_an_empty_xslt_file
	{
		It Should_cache_and_reuse_the_parent_stylesheet;
	}
}
