//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------
namespace Kelp.Test.Extensions
{
	using System;

	using Kelp.Core.Extensions;
	using Machine.Specifications;

	[Subject(typeof(DateTimeExtensions)), Tags(Categories.Core)]
	public class When_using_the_datetime_extensions
	{
		private static DateTime x;

		private Establish ctx = () =>
		{
			x = new DateTime(2000, 1, 1);
		};

		private Because of = () => x.Offset("+2d");

		private It Should_correctly_add_two_days = () => x.Offset("+2d").Day.ShouldEqual(3);
		private It Should_correctly_add_two_years = () => x.Offset("+2y").Year.ShouldEqual(2002);
		private It Should_correctly_substract_four_months = () => x.Offset("-4M").Month.ShouldEqual(9);
		private It Should_correctly_substract_four_months_and_change_the_year = () => x.Offset("-4M").Year.ShouldEqual(1999);
		private It Should_correctly_add_1000_years = () => x.Offset("1000y").Year.ShouldEqual(3000);
	}
}