//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------
namespace Kelp.Test.Extensions
{
	using System;
	using System.Collections.Generic;

	using Kelp.Core.Extensions;
	using Machine.Specifications;

	[Subject(typeof(IEnumerableExtensions)), Tags(Categories.Core)]
	public class When_using_ienumerable_extensions
	{
		private static List<string> myList = new List<string> { "red", "green", "blue" };

		private It Should_correctly_join_using_comma = () => myList.Join(",").ShouldEqual("red,green,blue");
		private It Should_correctly_join_using_pipe = () => myList.Join("|").ShouldEqual("red|green|blue");
		private It Should_correctly_join_using_character = () => myList.Join("d").ShouldEqual("reddgreendblue");
		private It Should_correctly_join_using_empty = () => myList.Join(string.Empty).ShouldEqual("redgreenblue");
		private It Should_correctly_join_using_string = () => myList.Join(" ++ ").ShouldEqual("red ++ green ++ blue");
		private It Should_throw_an_error_using_null = () => Catch.Exception(() => myList.Join(null)).ShouldBeOfType<ArgumentNullException>();
	}
}