// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>
/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace Kelp.Test.Extensions
{
	using System;
	using System.Linq;
	using System.Collections.Generic;

	using Kelp.Extensions;
	using Machine.Specifications;

	// ReSharper disable StringCompareToIsCultureSpecific

	[Subject(typeof(ListExtensions)), Tags(Categories.Core)]
	public class When_ordering_using_delegate
	{
		private static List<TestSubject> subjects;

		private Establish ctx = () =>
		{
			subjects = new List<TestSubject>
			{
				new TestSubject { Name = "John", Length = 180 },
				new TestSubject { Name = "Marvin", Length = 184 },
				new TestSubject { Name = "Adam", Length = 190 },
				new TestSubject { Name = "William", Length = 169 },
				new TestSubject { Name = "Gabriel", Length = 174 },
				new TestSubject { Name = "Fritz", Length = 199 },
			};
		};

		private It Should_correctly_sort_on_name = () => subjects.OrderBy((s1, s2) => s1.Name.CompareTo(s2.Name))
			.ElementAt(0).Name.ShouldEqual("Adam");

		private It Should_correctly_sort_on_length = () => subjects.OrderBy((s1, s2) => s1.Length.CompareTo(s2.Length))
			.ElementAt(0).Name.ShouldEqual("William");
	}

	internal class TestSubject
	{
		public string Name { get; set; }

		public int Length { get; set; }
	}
}
