// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>
/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace Sage.Test
{
	using Machine.Specifications;

	[Subject(typeof(UrlGenerator)), Tags(Categories.Core)]
	public class When_generating_urls_without_active_querystring
	{
		static SageContext sageContext;

		Establish testContext = () =>
		{
			sageContext = Mother.CreateSageContext("/");
			sageContext.ProjectConfiguration.Linking.SetApplicationPath("/");
			sageContext.ProjectConfiguration.Linking.AddLink("link1", "customers");
			sageContext.ProjectConfiguration.Linking.AddLink("link2", "customers/{id}/{name}");
		};

		It Should_generate_a_proper_link_without_placeholders = () =>
			sageContext.Url.GetUrl("link1").ShouldEqual("/customers");

		It Should_generate_a_proper_link_with_placeholders = () =>
			sageContext.Url.GetUrl("link2", "id=123&name=julius").ShouldEqual("/customers/123/julius");
	}
}
