//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kelp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        private Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kelp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or an empty string..
        /// </summary>
        private static string Arg_NullOrEmpty {
            get {
                return ResourceManager.GetString("Arg_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include location identifies an attribute or namespace node!.
        /// </summary>
        private static string AttributeOrNamespaceInIncludeLocationError {
            get {
                return ResourceManager.GetString("AttributeOrNamespaceInIncludeLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular inclusion has been detected, inclusion location: {0}..
        /// </summary>
        private static string CircularInclusion {
            get {
                return ResourceManager.GetString("CircularInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular inclusion has been detected, inclusion location: {0}. In {1}, Line {2}, Position {3}..
        /// </summary>
        private static string CircularInclusionLong {
            get {
                return ResourceManager.GetString("CircularInclusionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumflex character must be escaped in XPointer..
        /// </summary>
        private static string CircumflexCharMustBeEscaped {
            get {
                return ResourceManager.GetString("CircumflexCharMustBeEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occured during GetEntity call to custom XmlResolver..
        /// </summary>
        private static string CustomXmlResolverError {
            get {
                return ResourceManager.GetString("CustomXmlResolverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom XmlResolver returned null..
        /// </summary>
        private static string CustomXmlResolverReturnedNull {
            get {
                return ResourceManager.GetString("CustomXmlResolverReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom XmlResolver returned object of an unsupported type &apos;{0}&apos;..
        /// </summary>
        private static string CustomXmlResolverReturnedUnsupportedType {
            get {
                return ResourceManager.GetString("CustomXmlResolverReturnedUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in element() scheme data: empty XPointer..
        /// </summary>
        private static string EmptyElementSchemeXPointer {
            get {
                return ResourceManager.GetString("EmptyElementSchemeXPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xi:fallback element must be direct child of xi:include element. Location: {0}..
        /// </summary>
        private static string FallbackNotChildOfInclude {
            get {
                return ResourceManager.GetString("FallbackNotChildOfInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xi:fallback element must be direct child of xi:include element. Location: {0}, Line {1}, Position {2}..
        /// </summary>
        private static string FallbackNotChildOfIncludeLong {
            get {
                return ResourceManager.GetString("FallbackNotChildOfIncludeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource error has occured and no fallback has been provided: {0}..
        /// </summary>
        private static string FatalResourceException {
            get {
                return ResourceManager.GetString("FatalResourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment identifiers must not be used in &apos;href&apos; attribute..
        /// </summary>
        private static string FragmentIDInHref {
            get {
                return ResourceManager.GetString("FragmentIDInHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xi:include element cannot be child of xi:include element. Location: {0}..
        /// </summary>
        private static string IncludeChildOfInclude {
            get {
                return ResourceManager.GetString("IncludeChildOfInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xi:include element cannot be child of xi:include element. Location: {0}, Line {1}, Position {2}..
        /// </summary>
        private static string IncludeChildOfIncludeLong {
            get {
                return ResourceManager.GetString("IncludeChildOfIncludeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the first argument of key() function must be string..
        /// </summary>
        private static string IndexingXPathNavigator_KeyArgumentNotString {
            get {
                return ResourceManager.GetString("IndexingXPathNavigator_KeyArgumentNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of arguments of key() function..
        /// </summary>
        private static string IndexingXPathNavigator_KeyWrongArguments {
            get {
                return ResourceManager.GetString("IndexingXPathNavigator_KeyWrongArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIncludingReader doesn&apos;t support intra-document references..
        /// </summary>
        private static string IntradocumentReferencesNotSupported {
            get {
                return ResourceManager.GetString("IntradocumentReferencesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;accept&apos; attribute contains a character not allowed in HTTP header: 0x{0}..
        /// </summary>
        private static string InvalidCharForAccept {
            get {
                return ResourceManager.GetString("InvalidCharForAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name token: {0}:{1}..
        /// </summary>
        private static string InvalidNameToken {
            get {
                return ResourceManager.GetString("InvalidNameToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        private static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token after shorthand pointer..
        /// </summary>
        private static string InvalidTokenAfterShorthandPointer {
            get {
                return ResourceManager.GetString("InvalidTokenAfterShorthandPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in element() scheme data: Invalid token in ChildSequence, a closing round bracket was expected..
        /// </summary>
        private static string InvalidTokenInElementSchemeWhileClosingRoundBracketExpected {
            get {
                return ResourceManager.GetString("InvalidTokenInElementSchemeWhileClosingRoundBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in element() scheme data: Invalid token in ChildSequence, a number was expected..
        /// </summary>
        private static string InvalidTokenInElementSchemeWhileNumberExpected {
            get {
                return ResourceManager.GetString("InvalidTokenInElementSchemeWhileNumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in xmlns() scheme data: Invalid token in XmlnsSchemaData, equal sign was expected..
        /// </summary>
        private static string InvalidTokenInXmlnsSchemeWhileEqualsSignExpected {
            get {
                return ResourceManager.GetString("InvalidTokenInXmlnsSchemeWhileEqualsSignExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in xmlns() scheme data: Invalid token in XmlnsSchemaData, NCName was expected..
        /// </summary>
        private static string InvalidTokenInXmlnsSchemeWhileNCNameExpected {
            get {
                return ResourceManager.GetString("InvalidTokenInXmlnsSchemeWhileNCNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI &apos;{0}&apos;..
        /// </summary>
        private static string InvalidURI {
            get {
                return ResourceManager.GetString("InvalidURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error while reading resource &apos;{0}&apos;..
        /// </summary>
        private static string IOErrorWhileFetchingResource {
            get {
                return ResourceManager.GetString("IOErrorWhileFetchingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed XInclusion result - xi:include element at the top level must include a single element and optional comments and PIs..
        /// </summary>
        private static string MalformedXInclusionResult {
            get {
                return ResourceManager.GetString("MalformedXInclusionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;href&apos; or &apos;xpointer&apos; attributes can&apos;t both be omitted on xi:include element. Location: {0}.&quot;.
        /// </summary>
        private static string MissingHrefAndXpointerException {
            get {
                return ResourceManager.GetString("MissingHrefAndXpointerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;href&apos; or &apos;xpointer&apos; attributes can&apos;t both be omitted on xi:include element. Location: {0}, Line {1}, Position {2}..
        /// </summary>
        private static string MissingHrefAndXpointerExceptionLong {
            get {
                return ResourceManager.GetString("MissingHrefAndXpointerExceptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attributes exposed.
        /// </summary>
        private static string NoAttributesExposed {
            get {
                return ResourceManager.GetString("NoAttributesExposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included document contains a character not allowed in XML: 0x{0}..
        /// </summary>
        private static string NonXmlCharacter {
            get {
                return ResourceManager.GetString("NonXmlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPointer &apos;{0}&apos; doesn&apos;t identify any subresources in document &apos;{1}&apos;..
        /// </summary>
        private static string NoSubresourcesIdentifiedException {
            get {
                return ResourceManager.GetString("NoSubresourcesIdentifiedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported encoding &apos;{0}&apos;..
        /// </summary>
        private static string NotSupportedEncoding {
            get {
                return ResourceManager.GetString("NotSupportedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPointer pointer cannot be null..
        /// </summary>
        private static string NullXPointer {
            get {
                return ResourceManager.GetString("NullXPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory error while reading resource &apos;{0}&apos;..
        /// </summary>
        private static string OutOfMemoryWhileFetchingResource {
            get {
                return ResourceManager.GetString("OutOfMemoryWhileFetchingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; cannot be fetched..
        /// </summary>
        private static string ResourceError {
            get {
                return ResourceManager.GetString("ResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security exception while fetching &apos;{0}&apos;..
        /// </summary>
        private static string SecurityException {
            get {
                return ResourceManager.GetString("SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in xmlns() scheme data: {0}.
        /// </summary>
        private static string SyntaxErrorInXmlnsSchemeData {
            get {
                return ResourceManager.GetString("SyntaxErrorInXmlnsSchemeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in xpath1() scheme data: {0}.
        /// </summary>
        private static string SyntaxErrorInXPath1SchemeData {
            get {
                return ResourceManager.GetString("SyntaxErrorInXPath1SchemeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in xpointer() scheme data: {0}.
        /// </summary>
        private static string SyntaxErrorInXPointerSchemeData {
            get {
                return ResourceManager.GetString("SyntaxErrorInXPointerSchemeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xi:include element cannot contain more than one xi:fallback element. Location: {0}..
        /// </summary>
        private static string TwoFallbacks {
            get {
                return ResourceManager.GetString("TwoFallbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xi:include element cannot contain more than one xi:fallback element. Location: {0}, Line {1}, Position {2}..
        /// </summary>
        private static string TwoFallbacksLong {
            get {
                return ResourceManager.GetString("TwoFallbacksLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeclared prefix &apos;{0}&apos;..
        /// </summary>
        private static string UndeclaredPrefix {
            get {
                return ResourceManager.GetString("UndeclaredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of scheme data..
        /// </summary>
        private static string UnexpectedEndOfSchemeData {
            get {
                return ResourceManager.GetString("UnexpectedEndOfSchemeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown &apos;parse&apos; attribute value: &apos;{0}&apos;..
        /// </summary>
        private static string UnknownParseAttrValue {
            get {
                return ResourceManager.GetString("UnknownParseAttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown &apos;parse&apos; attribute value: &apos;{0}&apos;. In {1}, Line {2}, Position {3}..
        /// </summary>
        private static string UnknownParseAttrValueLong {
            get {
                return ResourceManager.GetString("UnknownParseAttrValueLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown element in the XInclude namespace has been detected: {0}..
        /// </summary>
        private static string UnknownXIncludeElement {
            get {
                return ResourceManager.GetString("UnknownXIncludeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve URI reference &apos;{0}&apos;..
        /// </summary>
        private static string UnresolvableURI {
            get {
                return ResourceManager.GetString("UnresolvableURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI schema is not supported: &apos;{0}&apos;..
        /// </summary>
        private static string URISchemaNotSupported {
            get {
                return ResourceManager.GetString("URISchemaNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root element is missing..
        /// </summary>
        private static string Xml_MissingRoot {
            get {
                return ResourceManager.GetString("Xml_MissingRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XmlDocument instance can only be used for serialization purposes..
        /// </summary>
        private static string XmlDocumentFactory_NotImplementedDOM {
            get {
                return ResourceManager.GetString("XmlDocumentFactory_NotImplementedDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to read past EOF..
        /// </summary>
        private static string XmlFragmentStream_EOF {
            get {
                return ResourceManager.GetString("XmlFragmentStream_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XPath query was not executed against an XmlNode-based object (such as XmlDocument)..
        /// </summary>
        private static string XmlNodeListFactory_IHasXmlNodeMissing {
            get {
                return ResourceManager.GetString("XmlNodeListFactory_IHasXmlNodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort expression must be either a string or an XPathExpression..
        /// </summary>
        private static string XPathCache_BadSortObject {
            get {
                return ResourceManager.GetString("XPathCache_BadSortObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add new elements after the iterator has moved..
        /// </summary>
        private static string XPathNavigatorIterator_CantAddAfterMove {
            get {
                return ResourceManager.GetString("XPathNavigatorIterator_CantAddAfterMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in element() scheme data: 0 index in ChildSequence..
        /// </summary>
        private static string ZeroIndexInElementSchemechildSequence {
            get {
                return ResourceManager.GetString("ZeroIndexInElementSchemechildSequence", resourceCulture);
            }
        }
    }
}
