// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>

/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local
namespace Sage.Test.ResourceManagement
{
	using System;
	using System.Xml;

	using Kelp.Extensions;

	using Machine.Specifications;
	using Sage.Configuration;

	[Subject(typeof(LocaleInfo)), Tags(Categories.ResourceManagement)]
	public class When_requesting_info_on_english_locale
	{
		private static LocaleInfo localeInfo;
		private static XmlDocument xmlDocument = new XmlDocument();

		private Establish ctx = () =>
			{
				xmlDocument.LoadXml(string.Format(@"
					<internationalization xmlns='{0}'>
						<locale name=""uk"" dictionaryNames=""en-UK,en"" resourceNames=""en-UK,en,default"">
							<format culture=""en-uk"" shortDate=""d"" longDate=""D""/>
						</locale>
					</internationalization>", XmlNamespaces.ProjectConfigurationNamespace));

				XmlNamespaceManager nm = XmlNamespaces.Manager;
				XmlElement localeNode = xmlDocument.SelectSingleElement("//p:locale", nm);
				localeInfo = new LocaleInfo(localeNode);
			};

		private It Should_have_the_correct_name = () => 
			localeInfo.Name.ShouldEqual("uk");

		private It Should_have_the_correct_resource_name = () => 
			localeInfo.ResourceNames[0].ShouldEqual("en-UK");

		private It Should_have_the_same_resource_name_as_the_dictionary_name = () => 
			localeInfo.ResourceNames[0].ShouldEqual(localeInfo.DictionaryNames[0]);

		private It Should_have_the_default_fallback_resource_name = () => 
			localeInfo.ResourceNames[2].ShouldEqual("default");
	}

	[Subject(typeof(LocaleInfo)), Tags(Categories.ResourceManagement)]
	public class When_requesting_an_empty_locale
	{
		private static LocaleInfo localeInfo;
		private static Exception exception;

		private Because of = () => exception = Catch.Exception(() => localeInfo = new LocaleInfo(null));

		private It Should_Fail = () => exception.ShouldBeAssignableTo<ArgumentNullException>();
	}
}