// <auto-generated>Marked as auto-generated so StyleCop will ignore BDD style tests</auto-generated>

/**
 * Copyright 2012 Igor France
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local
namespace Sage.Test.ResourceManagement
{
	using Machine.Specifications;

	using Sage.Configuration;
	using Sage.ResourceManagement;

	[Subject(typeof(XmlResource)), Tags(Categories.ResourceManagement)]
	public class When_loading_an_xml_resource
	{
		static SageContext context = Mother.CreateSageContext("default", "fr");

		It Should_load_the_french_file_properly = () =>
			new XmlResource(context.MapPath("~/assets/default/views/home/index.xml"), context)
				.Load("fr")
				.DocumentElement.InnerText.ShouldContain("french");

		It Should_load_the_german_file_properly = () =>
			new XmlResource(context.MapPath("~/assets/default/views/home/index.xml"), context)
				.Load("de")
				.DocumentElement.InnerText.ShouldContain("german");
	}
}