namespace Sage.Controllers
{
	using System;

	/// <summary>
	/// Indicates that a method should be used to filter or enhance the view XML generated by <see cref="SageController"/>
	/// </summary>
	/// <see cref="SageController.GetViewXml"/>
	[AttributeUsage(AttributeTargets.Method)]
	public class ViewXmlFilterAttribute : Attribute
	{
	}
}
