//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local
namespace Sage.Test.Dev
{
	using System;
	using System.Collections.Generic;
	using System.IO;

	using Machine.Specifications;

	using Sage.Configuration;
	using Sage.Resources.DevTools;

	[Subject(typeof(PackageManager)), Tags(Categories.DevTools)]
	public class When_installing_embedded_resources
	{
		private static List<String> resources;
		private static SageContext context;
		private static string targetPath;
		private static string webPath;

		private Establish ctx = () => 
			{
				context = Mother.CreateSageContext("home");
				targetPath = context.Path.PhysicalSharedViewPath;
				webPath = context.Path.SharedViewPath;
				resources = PackageManager.GetPackageResources(targetPath);
			};

		private It Should_return_multiple_resources = () => resources.Count.ShouldBeGreaterThan(0);

		private It Should_properly_install_resources = () =>
			{
				PackageManager.InstallResourcesTo(targetPath, webPath);
				foreach (var item in resources)
				{
					Console.WriteLine("Exists? " + item);
					File.Exists(item).ShouldBeTrue();
				}
			};
	}
}
